version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitbit
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fitbit_backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - timescaledb

  frontend:
    build: ./frontend
    container_name: fitbit_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  timescaledb_data:
